"""Stage A1/A2: where each method stops keeping nuclei, and the section-4 rule verdicts.

Reads runs/fidelity/results_all.csv (scripts/fidelity/results_table.py) and writes
  runs/fidelity/a1_crossings.csv  -- per frame x detector x method family: the compression
                                     ratio (and, for Luxar, splats per nucleus) at which
                                     nuclei kept first falls below 95% and 90%
  runs/fidelity/rule_check_a1.md  -- verdicts of paper/DECISION_RULES.md section 4

Crossing: rows sorted from least to most compressed; the crossing lies between the last
row at or above the threshold and the first row below it, interpolated linearly in
log(ratio) (or log(splats per nucleus)). If no row falls below, the crossing is beyond the
most compressed row ('>'); if the least compressed row is already below, it is before it ('<').
Match radius 0.6 D throughout.
"""
from pathlib import Path

import numpy as np
import pandas as pd

REPO = Path(__file__).resolve().parents[2]
F = REPO / 'runs' / 'fidelity'
KEY = 'kept@r0.6'
THRESH = (0.95, 0.90)
MIN_FRAC = 0.75                       # a claim holds on >= 75% of frames (6 of 8)
GAP_PTS = 0.05
CLIFF_MAX_SPN = 3.5


def crossing(x, kept, thr, decreasing_x=False):
    """x: compression axis; returns (value, qualifier) with qualifier '', '>' or '<'."""
    order = np.argsort(-x if decreasing_x else x)
    x, kept = np.asarray(x)[order], np.asarray(kept)[order]
    below = np.where(kept < thr)[0]
    if len(below) == 0:
        return x[-1], '>' if not decreasing_x else '<'
    i = below[0]
    if i == 0:
        return x[0], '<' if not decreasing_x else '>'
    x0, x1, k0, k1 = np.log(x[i - 1]), np.log(x[i]), kept[i - 1], kept[i]
    return float(np.exp(x0 + (thr - k0) / (k1 - k0) * (x1 - x0))), ''


def crossings(df):
    rows = []
    for (frame, det, fam), g in df[df.family != 'raw'].groupby(['frame', 'detector', 'family']):
        r = dict(frame=frame, role=g.role.iloc[0], n_labels=g.n_labels.iloc[0], detector=det,
                 family=fam, n_points=len(g), max_ratio=g.ratio.max())
        for thr in THRESH:
            v, q = crossing(g.ratio.values, g[KEY].values, thr)
            r[f'ratio@{thr:.2f}'] = f'{q}{v:.0f}'
            if fam == 'luxar' and g.splats_per_nucleus.notna().all():
                v, q = crossing(g.splats_per_nucleus.values, g[KEY].values, thr, decreasing_x=True)
                r[f'spn@{thr:.2f}'] = f'{q}{v:.1f}'
        rows.append(r)
    return pd.DataFrame(rows)


def gap(g):
    """JPEG-XL at its largest reachable ratio <= 120x minus Luxar at K=16000 (points)."""
    jx = g[(g.family == 'jpegxl') & (g.ratio <= 120)]
    lx = g[g.method == 'luxar_K16000']
    if jx.empty or lx.empty:
        return None
    return float(jx.loc[jx.ratio.idxmax(), KEY] - lx[KEY].iloc[0]), float(jx.ratio.max()), float(lx.ratio.iloc[0])


def verdict(ok, n, label):
    need = int(np.ceil(MIN_FRAC * n)) if n else 0
    if n == 0:
        return f'**{label}: NO DATA YET**'
    return f'**{label}: {"HOLDS" if ok >= need else "DOES NOT HOLD"}** ({ok} of {n} frames; needs {need})'


def main():
    df = pd.read_csv(F / 'results_all.csv')
    cr = crossings(df)
    cr.to_csv(F / 'a1_crossings.csv', index=False)
    L = ['# Section-4 rule check (stages A1-A2)', '',
         'Generated by scripts/fidelity/a1_crossings.py from runs/fidelity/results_all.csv; '
         'rules in paper/DECISION_RULES.md section 4. Match radius 0.6 D.', '']
    a1 = df[df.role == 'a1']

    # ---- A1 cliff: LoG, Luxar, 90% crossing in splats per nucleus
    L += ['## A1 cliff (LoG, Luxar: splats per nucleus where nuclei kept falls below 90%)', '']
    ok = n = 0
    for frame, g in a1[(a1.detector == 'log') & (a1.family == 'luxar')].groupby('frame'):
        v, q = crossing(g.splats_per_nucleus.values, g[KEY].values, 0.90, decreasing_x=True)
        lowest = g.loc[g.splats_per_nucleus.idxmin()]
        if q == '':
            holds, why = v <= CLIFF_MAX_SPN, f'crossing at {v:.1f} splats/nucleus'
        elif q == '<':          # even the smallest budget keeps >= 90%: upper bound
            holds, why = v <= CLIFF_MAX_SPN, (f'smallest budget ({v:.1f}/nucleus) still keeps '
                                              f'{lowest[KEY]:.2f}: crossing <= {v:.1f}'
                                              + ('' if v <= CLIFF_MAX_SPN else ' -> unresolved'))
        else:
            holds, why = False, f'below 90% already at {v:.1f}/nucleus (the largest budget)'
        n += 1
        ok += bool(holds)
        L.append(f'- {frame} ({int(g.n_labels.iloc[0])} nuclei): {why} -> {"yes" if holds else "no"}')
    L += ['', verdict(ok, n, f'A1 cliff <= {CLIFF_MAX_SPN} splats per nucleus'), '']

    # ---- A1 PSNR: Luxar PSNR range < 3 dB over K=1000-16000 while LoG kept range >= 0.15
    L += ['## A1 PSNR blindness (Luxar, K = 1000-16000)', '']
    ok = n = 0
    ks = [f'luxar_K{k}' for k in (1000, 1500, 2000, 4000, 16000)]
    for frame, g in a1[(a1.detector == 'log') & a1.method.isin(ks)].groupby('frame'):
        dp, dk = g.psnr.max() - g.psnr.min(), g[KEY].max() - g[KEY].min()
        holds = dp < 3 and dk >= 0.15
        n += 1
        ok += bool(holds)
        L.append(f'- {frame}: PSNR range {dp:.2f} dB, nuclei-kept range {dk:.2f} -> {"yes" if holds else "no"}')
    L += ['', verdict(ok, n, 'A1 PSNR cannot see the cliff'), '']

    # ---- detector dependence, per detector
    for det, label, roles in (('cellpose', 'A1 detector dependence (Cellpose, 2D stitched)', ('a1',)),
                              ('cellpose3d', 'A2 stitching (Cellpose 3D mode)', ('main', 'a1')),
                              ('watershed', 'A2 learned vs classical (3D watershed)', ('main', 'a1'))):
        L += [f'## {label}: JPEG-XL (largest ratio <= 120x) minus Luxar K=16000', '']
        ok = n = 0
        for frame, g in df[(df.detector == det) & df.role.isin(roles)].groupby('frame'):
            r = gap(g)
            if r is None:
                L.append(f'- {frame}: missing JPEG-XL <= 120x or Luxar K=16000')
                continue
            gp, rj, rl = r
            n += 1
            ok += gp >= GAP_PTS
            L.append(f'- {frame}: JPEG-XL {rj:.0f}x vs Luxar {rl:.0f}x: gap {100 * gp:+.1f} points')
        if det == 'watershed':
            need = int(np.ceil(MIN_FRAC * n)) if n else 0
            small = n - ok
            L += ['', (f'**{label}: gap < 5 points on {small} of {n} frames (needs {need}) -> '
                       + ('supports "learned segmenters are the sensitive ones"' if n and small >= need
                          else 'penalty is NOT specific to learned models' if n and ok >= need
                          else 'mixed: report per frame' if n else 'NO DATA YET') + '**'), '']
        else:
            L += ['', verdict(ok, n, label + ' gap >= 5 points'), '']

    (F / 'rule_check_a1.md').write_text('\n'.join(L) + '\n', encoding='utf-8')
    print('\n'.join(L))
    print(cr.to_string(index=False))


if __name__ == '__main__':
    main()
