"""95% bootstrap CIs (over labelled nuclei, paired across methods) for the paper's two key
comparisons, from cached detections -- no refitting.

  gap90  : Cellpose, JPEG-XL minus Luxar nuclei kept at 45-94x (detector dependence)
  hi230  : Luxar minus JPEG2000 nuclei kept near 230x, both detectors

Nuclei kept = hits(recon)/hits(raw) on the SAME resampled nuclei. Writes
runs/fidelity/bootstrap_ci.csv and paper/numbers_ci.tex.
"""
import importlib.util
from pathlib import Path

import numpy as np
import pandas as pd

REPO = Path(__file__).resolve().parents[2]
F = REPO / 'runs' / 'fidelity'
spec = importlib.util.spec_from_file_location('rd', REPO / 'scripts/fidelity/rate_detectability.py')
rd = importlib.util.module_from_spec(spec)
spec.loader.exec_module(rd)
FR = {('01', 150): ('ce_t150', 192), ('01', 194): ('ce_t194', 362),
      ('02', 150): ('ce_s02_t150', 190), ('02', 180): ('ce_s02_t180', 351)}
B, RNG = 2000, np.random.default_rng(0)


def hits(pred, gt, rad):
    h = np.zeros(len(gt), bool)
    if len(pred):
        _, ci, _ = rd.match_indices(pred * rd.V, gt * rd.V, rad)
        h[ci] = True
    return h


def main():
    ds = rd.DATASETS['CE']
    rd.configure(ds['voxel'], ds['nucleus_um'])
    rad = 0.6 * ds['nucleus_um']
    rows, tex = [], {}
    for (seq, t), (tag, n) in FR.items():
        gt = rd.gt_from_tra(ds['root'], t, [0, 0, 0], None, seq)
        crop, lo, hi = rd.load_crop(ds['root'], t, [0, 0, 0], None, seq)
        _, raw_log, _ = rd.ranked_candidates(rd.normalise(crop, lo, hi))
        H = {}
        for det in ('log', 'cellpose'):
            csv = pd.read_csv(F / f'{det}_{tag}.csv')
            csv['family'] = csv.method.str.replace(r'_K\d+$', '', regex=True)
            if det == 'log':
                H[(det, 'raw')] = hits(raw_log[:len(gt)], gt, rad)
                load = lambda f: np.load(F / f'log_{tag}_candidates' / f'{f}.log_ranked.npy')[:len(gt)]
            else:
                H[(det, 'raw')] = hits(np.load(F / f'cellpose_{tag}_centroids' / 'raw.centroids.npy'), gt, rad)
                load = lambda f: np.load(F / f'cellpose_{tag}_centroids' / f'{f}.centroids.npy')
            for _, r in csv[csv.method != 'raw'].iterrows():
                H[(det, r.file)] = (r.family, r.ratio, hits(load(r.file), gt, rad))

        def boot(det, pos, neg):
            """mean kept(pos rows) - mean kept(neg rows), resampling nuclei."""
            raw = H[(det, 'raw')]
            P = np.array([H[k][2] for k in pos]); N_ = np.array([H[k][2] for k in neg])
            idx = RNG.integers(0, len(raw), (B, len(raw)))
            r0 = raw[idx].sum(1)
            d = P[:, idx].sum(2).mean(0) / r0 - N_[:, idx].sum(2).mean(0) / r0
            full = P.sum(1).mean() / raw.sum() - N_.sum(1).mean() / raw.sum()
            return full, np.percentile(d, 2.5), np.percentile(d, 97.5)

        def sel(det, fam, lo_r, hi_r):
            return [k for k, v in H.items() if k[0] == det and k[1] != 'raw' and v[0] == fam and lo_r <= v[1] <= hi_r]

        f, a, b = boot('cellpose', sel('cellpose', 'jpegxl', 45, 94), sel('cellpose', 'luxar', 45, 94))
        rows.append(dict(frame=f's{seq} t{t}', comparison='gap90_cellpose_JXL_minus_Luxar', est=f, lo=a, hi=b))
        for det in ('log', 'cellpose'):
            lx = sel(det, 'luxar', 180, 300)
            j2 = sel(det, 'jpeg2k', 180, 300)
            if lx and j2:
                f, a, b = boot(det, lx, j2)
                rows.append(dict(frame=f's{seq} t{t}', comparison=f'hi230_{det}_Luxar_minus_J2K', est=f, lo=a, hi=b))
    df = pd.DataFrame(rows)
    df.to_csv(F / 'bootstrap_ci.csv', index=False)
    print(df.round(3).to_string(index=False))
    g = df[df.comparison.str.startswith('gap90')]
    hc = df[df.comparison.str.startswith('hi230_cellpose')]
    hl = df[df.comparison.str.startswith('hi230_log')]
    with open(REPO / 'paper' / 'numbers_ci.tex', 'w') as fh:
        fh.write('% generated by scripts/fidelity/bootstrap_ci.py -- do not edit\n')
        fh.write(f'\\newcommand{{\\GapCIfrac}}{{{int((g.lo > 0).sum())} of {len(g)}}}\n')
        fh.write(f'\\newcommand{{\\HiLoGCIfrac}}{{{int((hl.lo > 0).sum())} of {len(hl)}}}\n')
        fh.write(f'\\newcommand{{\\HiCPCIfrac}}{{{int((hc.lo > 0).sum())} of {len(hc)}}}\n')


if __name__ == '__main__':
    main()
