"""NON-CIRCULAR validation: does candidate generation find nuclei a HUMAN annotated?

Every coverage/F1 number so far was scored against targets produced by our own peak
detector, and under NMS=13 the candidate count matched the target count exactly in all
four Tribolium regions. That is circular: the spatial scale was effectively tuned to a
target definition generated by a related process.

The Drosophila (Fluo-N3DL-DRO) set carries MANUAL annotation -- 189 nuclei marked by a
human in frame 0. Scoring against those breaks the circularity.

IMPORTANT -- the annotation is SPARSE. 189 nuclei are marked in an embryo containing far
more (annotated nucleus voxels are 0.14% of bright voxels). Consequences:
    RECALL against the 189 is meaningful -- did we find the ones a human marked?
    PRECISION / F1 are NOT -- an unannotated detection is not a false positive.
So this reports recall at a MATCHED DETECTION BUDGET, which is the fair comparison:
a method that simply returns more points trivially gets more recall.

Tests two claims at once:
    (D) is "suppression radius ~ nucleus spacing" biologically valid, or an artefact of
        circular targets?  -> sweep the radius, see where recall actually peaks
    (F) does our detector beat classical blob detection?  -> LoG and DoG baselines

Usage:
    python scripts/manual_label_validation.py
"""
import json
from pathlib import Path

import numpy as np
import tifffile
from scipy.ndimage import gaussian_filter, maximum_filter, gaussian_laplace

from volsplat.ctc import percentile_normalize

REPO = Path(__file__).resolve().parent.parent
OUT = REPO / 'runs/manual_validation'
DRO = Path(r'D:/Download/train/Fluo-N3DL-DRO (1)/Fluo-N3DL-DRO')
MATCH_RADIUS = 3.0        # microns, ~40% of the 7.6 um manual nucleus spacing
MARGIN = 12
VOXEL_ZYX_UM = (2.03, 0.406, 0.406)


def nms_peaks(response, nms_radius_um, voxel_zyx_um, threshold=None):
    """Local maxima with a PHYSICALLY ISOTROPIC suppression footprint.

    A cubic footprint is wrong on anisotropic data: with DRO voxels of
    0.406 x 0.406 x 2.03 um, a 14-voxel cube suppresses 5.7 um in xy but 28 um in z,
    while nuclei sit only ~7.6 um apart -- so it merges nuclei along z. The footprint
    is therefore sized per axis so it spans the same distance in microns.
    """
    size = [max(1, int(2 * round(nms_radius_um / s)) + 1) for s in voxel_zyx_um]
    is_peak = maximum_filter(response, size=size) == response
    if threshold is not None:
        is_peak &= response > threshold
    coords = np.argwhere(is_peak)
    if len(coords) == 0:
        return coords.astype(np.float32), np.array([]), size
    vals = response[tuple(coords.T)]
    order = np.argsort(-vals)
    return coords[order].astype(np.float32), vals[order], size


def recall_at(detections, manual, n, voxel_zyx_um, radius_um=MATCH_RADIUS):
    """Fraction of manual nuclei matched by the top-`n` detections, in MICRONS."""
    if len(detections) == 0:
        return 0.0
    s = np.asarray(voxel_zyx_um, dtype=np.float32)
    d = detections[:n] * s
    m = manual * s
    dist = np.linalg.norm(m[:, None, :] - d[None, :, :], axis=-1)
    return float((dist.min(axis=1) <= radius_um).mean())


def main():
    OUT.mkdir(parents=True, exist_ok=True)

    print('Loading DRO frame 0 and manual annotation ...')
    vol = tifffile.imread(str(DRO / '01/t000.tif')).astype(np.float32)
    vol = percentile_normalize(vol)
    manual = np.load(REPO / 'runs/dro_manual_centroids.npy')

    # crop to the annotated region so the comparison is over annotated territory only
    lo = np.maximum(manual.min(axis=0).astype(int) - MARGIN, 0)
    hi = np.minimum(manual.max(axis=0).astype(int) + MARGIN + 1, np.array(vol.shape))
    roi = np.ascontiguousarray(vol[lo[0]:hi[0], lo[1]:hi[1], lo[2]:hi[2]])
    man = manual - lo
    print(f'  crop {roi.shape} = {roi.size/1e6:.1f}M voxels, {len(man)} manual nuclei')

    s = np.asarray(VOXEL_ZYX_UM, dtype=np.float32)
    mp = man * s
    d = np.linalg.norm(mp[:, None, :] - mp[None, :, :], axis=-1)
    np.fill_diagonal(d, np.inf)
    spacing = float(np.median(d.min(axis=1)))
    print(f'  manual nucleus spacing (median NN): {spacing:.1f} microns')
    print(f'  match radius: {MATCH_RADIUS} microns')
    print(f'  voxel size (z,y,x): {VOXEL_ZYX_UM} um -- z is '
          f'{VOXEL_ZYX_UM[0]/VOXEL_ZYX_UM[2]:.1f}x coarser\n')

    # smoothing must also be physically isotropic
    sig_vox = tuple(2.0 / np.asarray(VOXEL_ZYX_UM) * VOXEL_ZYX_UM[2])
    sm = gaussian_filter(roi, sigma=sig_vox)
    budgets = [189, 500, 1000, 2000, 5000]
    rows = []

    print('=== (D) suppression-radius sweep (PHYSICALLY isotropic footprint) ===')
    print(f'{"NMS um":>7s} {"footprint zyx":>15s} {"cands":>7s} ' +
          ' '.join(f'{"R@"+str(b):>8s}' for b in budgets) + f' {"R@all":>7s}')
    for r_um in [1.0, 2.0, 3.0, 4.0, 6.0, 8.0, 12.0]:
        coords, vals, fp = nms_peaks(sm, r_um, VOXEL_ZYX_UM, threshold=0.0)
        rec = [recall_at(coords, man, b, VOXEL_ZYX_UM) for b in budgets]
        rall = recall_at(coords, man, len(coords), VOXEL_ZYX_UM)
        rows.append(dict(method=f'peaks_{r_um}um', nms_um=r_um, n=len(coords),
                         **{f'R@{b}': rec[i] for i, b in enumerate(budgets)},
                         R_all=rall))
        print(f'{r_um:7.1f} {str(fp):>15s} {len(coords):7d} ' +
              ' '.join(f'{v:8.3f}' for v in rec) + f' {rall:7.3f}')

    print('\n=== (F) classical blob-detection baselines ===')
    print(f'{"method":>16s} {"candidates":>11s} ' +
          ' '.join(f'{"R@"+str(b):>8s}' for b in budgets) + f' {"R@all":>7s}')
    def sig_um(u):
        return tuple(u / np.asarray(VOXEL_ZYX_UM))

    baselines = {}
    for u in [1.0, 1.6, 2.4]:                    # LoG at physical scales
        baselines[f'LoG_{u}um'] = -gaussian_laplace(roi, sigma=sig_um(u)) * (u ** 2)
    for u1, u2 in [(0.8, 1.6), (1.6, 3.2)]:      # DoG at physical scales
        baselines[f'DoG_{u1}-{u2}um'] = (gaussian_filter(roi, sig_um(u1))
                                         - gaussian_filter(roi, sig_um(u2)))

    for name, resp in baselines.items():
        coords, vals, fp = nms_peaks(resp, 3.0, VOXEL_ZYX_UM, threshold=0.0)
        rec = [recall_at(coords, man, b, VOXEL_ZYX_UM) for b in budgets]
        rall = recall_at(coords, man, len(coords), VOXEL_ZYX_UM)
        rows.append(dict(method=name, nms_um=3.0, n=len(coords),
                         **{f'R@{b}': rec[i] for i, b in enumerate(budgets)},
                         R_all=rall))
        print(f'{name:>16s} {len(coords):11d} ' +
              ' '.join(f'{v:8.3f}' for v in rec) + f' {rall:7.3f}')

    import pandas as pd
    df = pd.DataFrame(rows)
    df.to_csv(OUT / 'manual_validation.csv', index=False)
    json.dump({'manual_spacing_voxels': spacing, 'n_manual': int(len(man)),
               'crop_shape': list(roi.shape), 'match_radius': MATCH_RADIUS,
               'note': 'annotation is sparse; recall is valid, precision is not'},
              open(OUT / 'meta.json', 'w'), indent=2)

    best = df.loc[df['R@1000'].idxmax()]
    print(f'\nBest recall @1000 detections: {best.method} '
          f'({best["R@1000"]:.3f})')
    print(f'Manual nucleus spacing was {spacing:.1f} voxels.')
    print(f'Outputs -> {OUT}')


if __name__ == '__main__':
    main()
